/**
 * Herbarium API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package dev.xavierc.herbarium.api.apis

import com.google.gson.Gson
import io.ktor.application.*
import io.ktor.auth.*
import io.ktor.http.*
import io.ktor.response.*
import dev.xavierc.herbarium.api.Paths
import io.ktor.locations.*
import io.ktor.routing.*
import dev.xavierc.herbarium.api.infrastructure.ApiPrincipal
import dev.xavierc.herbarium.api.models.PutDataRequest
import dev.xavierc.herbarium.api.repository.DataRepository
import dev.xavierc.herbarium.api.repository.GreenhouseRepository
import dev.xavierc.herbarium.api.repository.PlantRepository
import dev.xavierc.herbarium.api.utils.exceptions.NotFoundException
import io.ktor.request.*
import org.kodein.di.DI
import org.kodein.di.instance
import java.util.*

@KtorExperimentalLocationsAPI
fun Route.GreenhouseApi(di: DI) {
    val gson = Gson()
    val empty = mutableMapOf<String, Any?>()

    val greenhouseRepository by di.instance<GreenhouseRepository>()
    val plantRepository by di.instance<PlantRepository>()
    val dataRepository by di.instance<DataRepository>()

    authenticate("oauth") {
        delete<Paths.deleteGreenhouse> {
            val principal = call.authentication.principal<OAuthAccessTokenResponse>()!!

            call.respond(HttpStatusCode.NotImplemented)
        }
    }

//    authenticate("apiKey") {
    get<Paths.getGreenhouse> { request ->
//        val principal = call.authentication.principal<ApiPrincipal>()!!
        try {
            val greenhouse = greenhouseRepository.getGreenhouse(request.uuid)

            call.respond(HttpStatusCode.OK, greenhouse)
        } catch (e: NotFoundException) {
            call.respond(HttpStatusCode.NotFound)
        }
    }
//    }

    authenticate("oauth") {
        get<Paths.getGreenhousesOfUser> {
            val principal = call.authentication.principal<OAuthAccessTokenResponse>()!!

            val exampleContentType = "application/json"
            val exampleContentString = """{
              "tank_level" : {
                "type" : "M",
                "plant_uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                "value" : 0.14658129805029452,
                "timestamp" : "2000-01-23T04:56:07.000+00:00"
              },
              "last_timestamp" : "2000-01-23T04:56:07.000+00:00",
              "plants" : [ {
                "light_last_reading" : {
                  "type" : "M",
                  "plant_uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                  "value" : 0.14658129805029452,
                  "timestamp" : "2000-01-23T04:56:07.000+00:00"
                },
                "valve_status" : {
                  "type" : "V",
                  "plant_uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                  "value" : true,
                  "timestamp" : "2000-01-23T04:56:07.000+00:00"
                },
                "last_uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                "planted_at" : "2000-01-23T04:56:07.000+00:00",
                "position" : 0,
                "type" : {
                  "moisture_goal" : 80.0,
                  "name" : "Tomato",
                  "light_exposure_min_duration" : 14.0,
                  "id" : 6
                },
                "moisture_last_reading" : {
                  "type" : "M",
                  "plant_uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                  "value" : 0.14658129805029452,
                  "timestamp" : "2000-01-23T04:56:07.000+00:00"
                },
                "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                "light_strip_status" : {
                  "type" : "V",
                  "plant_uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                  "value" : true,
                  "timestamp" : "2000-01-23T04:56:07.000+00:00"
                }
              }, {
                "light_last_reading" : {
                  "type" : "M",
                  "plant_uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                  "value" : 0.14658129805029452,
                  "timestamp" : "2000-01-23T04:56:07.000+00:00"
                },
                "valve_status" : {
                  "type" : "V",
                  "plant_uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                  "value" : true,
                  "timestamp" : "2000-01-23T04:56:07.000+00:00"
                },
                "last_uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                "planted_at" : "2000-01-23T04:56:07.000+00:00",
                "position" : 0,
                "type" : {
                  "moisture_goal" : 80.0,
                  "name" : "Tomato",
                  "light_exposure_min_duration" : 14.0,
                  "id" : 6
                },
                "moisture_last_reading" : {
                  "type" : "M",
                  "plant_uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                  "value" : 0.14658129805029452,
                  "timestamp" : "2000-01-23T04:56:07.000+00:00"
                },
                "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                "light_strip_status" : {
                  "type" : "V",
                  "plant_uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
                  "value" : true,
                  "timestamp" : "2000-01-23T04:56:07.000+00:00"
                }
              } ],
              "name" : "name",
              "created_at" : "2000-01-23T04:56:07.000+00:00",
              "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
            }"""

            when (exampleContentType) {
                "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
                "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
                else -> call.respondText(exampleContentString)
            }
        }
    }

    authenticate("oauth") {
        post<Paths.postActuatorState> {
            val principal = call.authentication.principal<OAuthAccessTokenResponse>()!!

            call.respond(HttpStatusCode.NotImplemented)
        }
    }

    authenticate("oauth") {
        post<Paths.postGreenhouse> {
            val principal = call.authentication.principal<OAuthAccessTokenResponse>()!!

            call.respond(HttpStatusCode.NotImplemented)
        }
    }

//    authenticate("apiKey") {
    put<Paths.putData> { request ->
//        val principal = call.authentication.principal<ApiPrincipal>()!!
        val payload: PutDataRequest = call.receive()

        // Check if greenhouse exists
        if (!greenhouseRepository.exist(request.uuid)) {
            call.respond(HttpStatusCode.NotFound)
        }

        val plantsUuid = mutableListOf<UUID>()
        payload.sensors.forEach {
            if (it.plantUuid != null) {
                plantsUuid.add(it.plantUuid)
            }
        }
        payload.actuators.forEach {
            if (it.plantUuid != null && !plantsUuid.contains(it.plantUuid)) {
                plantsUuid.add(it.plantUuid)
            }
        }

        // Check if plants exists
        val unknownPlants = plantRepository.exists(plantsUuid)

        // Remove unknown UUID
        val filteredSensorsData = payload.sensors.toMutableList()
        filteredSensorsData.removeIf {
            it.plantUuid in unknownPlants
        }
        val filteredActuatorsData = payload.actuators.toMutableList()
        filteredActuatorsData.removeIf {
            it.plantUuid in unknownPlants
        }

        dataRepository.insertSensorDataBatch(request.uuid, filteredSensorsData)
        dataRepository.insertActuatorStateBatch(request.uuid, filteredActuatorsData)

        call.respond(HttpStatusCode.OK, mapOf("unknown_plants" to unknownPlants))
    }
//    }

    authenticate("oauth") {
        put<Paths.putGreenHouse> {
            val principal = call.authentication.principal<OAuthAccessTokenResponse>()!!

            call.respond(HttpStatusCode.NotImplemented)
        }
    }
}
