/**
 * Herbarium API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package dev.xavierc.herbarium.api.apis

import com.google.gson.Gson
import io.ktor.application.*
import io.ktor.http.*
import io.ktor.response.*
import dev.xavierc.herbarium.api.Paths
import dev.xavierc.herbarium.api.applicationConfiguration
import io.ktor.locations.*
import io.ktor.routing.*

@KtorExperimentalLocationsAPI
fun Route.HealthApi() {
    val gson = Gson()

    get<Paths.getHealth> {
        val appConfig = applicationConfiguration()

        call.respond(
            HttpStatusCode.OK,
            gson.toJson(mapOf("healthy" to true, "version" to appConfig.property("version").getString()))
        )
    }
}
