/**
* Herbarium API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.herbarium.api.models


/**
 * 
 * @param type Which type of actuator the data come from. L => Light strip section, V => Valve, P => Pump.
 * @param timestamp When the state was changed
 * @param &#x60;value&#x60; State of the actuator.
 * @param plantUuid Universal unique identifier
 */
data class ActuatorState(
    /* Which type of actuator the data come from. L => Light strip section, V => Valve, P => Pump. */
    val type: ActuatorState.Type,
    /* When the state was changed */
    val timestamp: java.time.OffsetDateTime,
    /* State of the actuator. */
    val `value`: kotlin.Boolean,
    /* Universal unique identifier */
    val plantUuid: java.util.UUID? = null
) 
{
    /**
    * Which type of actuator the data come from. L => Light strip section, V => Valve, P => Pump.
    * Values: v,l,p
    */
    enum class Type(val value: kotlin.String){
        v("V"),
        l("L"),
        p("P");
    }
}

