/**
* Herbarium API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.herbarium.api.models


/**
 * 
 * @param code 
 */
data class ApiErrorResponse(
    val code: ApiErrorResponse.Code? = null
) 
{
    /**
    * 
    * Values: PLANT_POSITION_INVALID, PLANT_POSITION_ALREADY_OCCUPIED
    */
    enum class Code(val value: kotlin.String){
        PLANT_POSITION_INVALID("PLANT_POSITION_INVALID"),
        PLANT_POSITION_ALREADY_OCCUPIED("PLANT_POSITION_ALREADY_OCCUPIED")
    }
}

