/**
* Herbarium API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.herbarium.api.models


/**
 * 
 * @param uuid Universal unique identifier
 */
data class InlineResponse200(
    /* Universal unique identifier */
    val uuid: java.util.UUID? = null
) 

