/**
* Herbarium API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.herbarium.api.models

import com.google.gson.annotations.SerializedName


/**
 * 
 * @param id Unique identifier of the type.
 * @param name Name of the plant.
 * @param moistureGoal Percentage of moisture needed for the plant to perfectly grow.
 * @param lightExposureMinDuration Number of hour needed for the plant to perfectly grow.
 */
data class PlantType(
    /* Unique identifier of the type. */
    val id: Int,
    /* Name of the plant. */
    val name: kotlin.String,
    /* Percentage of moisture needed for the plant to perfectly grow. */
    @SerializedName(value = "moisture_goal")
    val moistureGoal: Double,
    /* Number of hour needed for the plant to perfectly grow. */
    @SerializedName(value = "light_exposure_min_duration")
    val lightExposureMinDuration: Double,
    /* How many days the germination can take. */
    @SerializedName(value = "germination_time")
    val germinationTime: Int,
    /* How many days the plant can take to growth. */
    @SerializedName(value = "growing_time")
    val growingTime: Int,
) 

