/**
* Herbarium API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.herbarium.api.models

import com.google.gson.annotations.SerializedName
import org.joda.time.DateTime

/**
 * Body send to the API when a plant is planted
 * @param position
 * @param plantedAt
 */
data class PutPlantRequest(
    val position: Int,
    @SerializedName(value = "planted_at")
    val plantedAt: DateTime
) 

