/**
* Herbarium API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.herbarium.api.models


/**
 * 
 * @param type Which type of sensor the data come from. M => Moisture sensor, L => Light sensor, T => Tank level sensor
 * @param timestamp When the data was read
 * @param &#x60;value&#x60; Value read by the sensor
 * @param plantUuid Universal unique identifier
 */
data class SensorData(
    /* Which type of sensor the data come from. M => Moisture sensor, L => Light sensor, T => Tank level sensor */
    val type: SensorData.Type,
    /* When the data was read */
    val timestamp: java.time.OffsetDateTime,
    /* Value read by the sensor */
    val `value`: java.math.BigDecimal,
    /* Universal unique identifier */
    val plantUuid: java.util.UUID? = null
) 
{
    /**
    * Which type of sensor the data come from. M => Moisture sensor, L => Light sensor, T => Tank level sensor
    * Values: m,l,t
    */
    enum class Type(val value: kotlin.String){
        m("M"),
        l("L"),
        t("T");
    }
}

