/**
* Herbarium API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.herbarium.api.models

import com.google.gson.annotations.SerializedName
import org.joda.time.DateTime


/**
 * 
 * @param type Which type of sensor the data come from. M => Moisture sensor, L => Light sensor, T => Tank level sensor
 * @param timestamp When the data was read
 * @param value Value read by the sensor
 * @param plantUuid Universal unique identifier
 */
data class SensorData(
    /* Which type of sensor the data come from. M => Moisture sensor, L => Light sensor, T => Tank level sensor */
    val type: Type,
    /* When the data was read */
    val timestamp: DateTime,
    /* Value read by the sensor */
    val value: Double,
    /* Universal unique identifier */
    @SerializedName("plant_uuid")
    val plantUuid: java.util.UUID? = null
) 
{
    /**
    * Which type of sensor the data come from. M => Moisture sensor, L => Light sensor, T => Tank level sensor
    * Values: m,l,t
    */
    enum class Type(val value: Char){
        M('M'),
        L('L'),
        T('T');
    }
}

